###
POST {{host}}:{{port}}/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username = {{username}} &
password = {{password}}

> {%
    console.log(response.body);
    client.global.set("token", response.body.token);
%}

###
# Start Game
POST {{host}}:{{port}}/admin/start
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}